// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NETCoreAPI_CodeFirst.Models;

namespace NETCoreAPI_CodeFirst.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NETCoreAPI_CodeFirst.Models.Class", b =>
                {
                    b.Property<int>("intId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("intAcademicYear");

                    b.Property<int>("intQuantity");

                    b.Property<string>("strCode");

                    b.Property<string>("strName");

                    b.HasKey("intId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("NETCoreAPI_CodeFirst.Models.Student", b =>
                {
                    b.Property<int>("intId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Class_Id");

                    b.Property<DateTime>("dateBirth");

                    b.Property<string>("strCode");

                    b.Property<string>("strName");

                    b.HasKey("intId");

                    b.HasIndex("Class_Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("NETCoreAPI_CodeFirst.Models.Student", b =>
                {
                    b.HasOne("NETCoreAPI_CodeFirst.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("Class_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
